[project]
name = "."
mode = "owner"
created = "2025-12-05T16:52:27.714136+00:00"

[dev]
type = "docker"

[frontends]
allowed = ["claude"]
default = "claude"

[embeddings]
model = "e5-base-v2"

[environment]
os = "macos"
arch = "aarch64"
detected_tools = [
    "gh",
    "git",
    "vim",
    "cargo-clippy",
    "jq",
    "wasm-pack",
    "brew",
    "docker",
    "claude",
    "cargo",
    "go",
    "nvim",
    "cargo-fmt",
]
