[version]
current = "0.8.4"
phase = 8
phase_name = "Go Public"
milestone = 4

[metadata]
history_file = "layer/surface/build/feat/go-public/version-history.md"
last_bump = "2026-01-26T11:43:14.788348+00:00"
