os = "macos"
arch = "aarch64"
home_dir = "/Users/nicabar"
current_dir = "/Users/nicabar/Projects/Sandbox/AI/RUST/patina"

[tools.vim]
available = true
version = "VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jul 11 2025 21:28:27)"
path = "/usr/bin/vim"

[tools.gh]
available = true
version = "gh version 2.82.1 (2025-10-22)"
path = "/opt/homebrew/bin/gh"

[tools.cargo-expand]
available = false

[tools.mysql]
available = false

[tools.sqlx]
available = false

[tools.go]
available = true
version = "go version go1.25.3 darwin/arm64"
path = "/opt/homebrew/bin/go"

[tools.apt]
available = false

[tools.cargo]
available = true
version = "cargo 1.89.0 (c24e10642 2025-06-23)"
path = "/Users/nicabar/.cargo/bin/cargo"

[tools.sccache]
available = false

[tools.psql]
available = false

[tools.code]
available = false

[tools.jq]
available = true
version = "jq-1.7.1-apple"
path = "/usr/bin/jq"

[tools.trunk]
available = false

[tools.cargo-edit]
available = false

[tools.cargo-audit]
available = false

[tools.docker]
available = true
version = "Docker version 28.5.1, build e180ab8"
path = "/usr/local/bin/docker"

[tools.brew]
available = true
version = "Homebrew 5.0.1"
path = "/opt/homebrew/bin/brew"

[tools.claude]
available = true
version = "2.0.1 (Claude Code)"
path = "/Users/nicabar/.nvm/versions/node/v23.3.0/bin/claude"

[tools.nvim]
available = true
version = "NVIM v0.11.4"
path = "/opt/homebrew/bin/nvim"

[tools.cargo-clippy]
available = true
version = "clippy 0.1.89 (29483883ee 2025-08-04)"
path = "/Users/nicabar/.cargo/bin/cargo-clippy"

[tools.wasm-pack]
available = true
version = "wasm-pack 0.13.1"
path = "/Users/nicabar/.cargo/bin/wasm-pack"

[tools.redis-cli]
available = false

[tools.sea-orm-cli]
available = false

[tools.cargo-watch]
available = false

[tools.yum]
available = false

[tools.cargo-release]
available = false

[tools.git]
available = true
version = "git version 2.39.5 (Apple Git-154)"
path = "/usr/bin/git"

[tools.docker-compose]
available = false

[tools.cargo-fmt]
available = true
version = "rustfmt 1.8.0-stable (29483883ee 2025-08-04)"
path = "/Users/nicabar/.cargo/bin/cargo-fmt"

[tools.cargo-outdated]
available = false

[languages.python]
available = true
version = "Python 3.11.7"

[languages.rust]
available = true
version = "rustc 1.89.0 (29483883e 2025-08-04)"
toolchain = "stable-aarch64-apple-darwin (overridden by environment variable RUSTUP_TOOLCHAIN)"

[languages.node]
available = true
version = "v23.3.0"

[env_vars]
RUSTUP_HOME = "/Users/nicabar/.rustup"
TERM = "xterm-256color"
USER = "nicabar"
CARGO_HOME = "/Users/nicabar/.cargo"
NVM_DIR = "/Users/nicabar/.nvm"
LANG = "en_US.UTF-8"
VISUAL = "code-insiders"
PATH = "32 paths (first 5: /opt/homebrew/opt/curl/bin:/Users/nicabar/Library/pnpm:/Users/nicabar/.bun/bin:/Users/nicabar/.nvm/versions/node/v23.3.0/bin:/Users/nicabar/.asdf/shims...)"
EDITOR = "code-insiders"
SHELL = "/bin/zsh"
HOME = "/Users/nicabar"
LC_ALL = "en_US.UTF-8"
